---
- name: Allow ping to windows hosts
  hosts: win_hosts
  become: yes
  gather_facts: false

  tasks:
    - name: Allow ping
      win_shell: |
        netsh advfirewall firewall add rule name="ICMP Allow incoming V4 echo request" protocol=icmpv4:8,any dir=in action=allow
        netsh advfirewall firewall add rule name="ICMP Allow incoming V6 echo request" protocol=icmpv6:8,any dir=in action=allow
