---
- name: Disable autologon
  hosts: win_all_desktops
  strategy: free
  become: yes
  gather_facts: false

  tasks:
    - name: Disable autologon
      win_shell: |
        $RegKey = “HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon”
        ForEach ($subkey in “AutoAdminLogon”, “DefaultPassword”)
        {
        if (Get-ItemProperty -Name $subkey -path $RegKey -ErrorAction SilentlyContinue)
        {
        Remove-ItemProperty -Path $RegKey -Name $subkey
        }
        }
