---
- name: "Configure decryptmalfoy RANGE Windows Domain Controller GPO"
  hosts: addc_srv1_b
  gather_facts: no
  vars_files:
    - ../vars/vars.yml
  tags:
    - addc
    - domain
    - network
    - share
    - winrm
    - users
    - groups
    - server
    - windows
    - firewall
    - decryptmalfoy
    - scenariob

  tasks:
    - ansible.builtin.include_tasks: configure-addc-gpo.yml
      vars:
        domain_shortname: "{{ domain_info_decryptmalfoy.shortname }}"
        domain_dns_name: "{{ domain_info_decryptmalfoy.dns_domain_name }}"
        domain_admin_user: "{{ domain_info_decryptmalfoy.admin_user }}"
        domain_admin_pass: "{{ domain_info_decryptmalfoy.admin_pass }}"
        domain_tld: "{{ domain_info_decryptmalfoy.tld }}"
        ad_ip_addr: "{{ domain_info_decryptmalfoy.ad_ip_addr }}"
        evals_range: "{{ evals_cycle }}"
        gpo_src_dir: "../files/gpo/vault12"
        gpo_dst_dir: "C:/deploy/vault12"
        deploy_dir: "C:/deploy"
