---
- name: Install programs on all Windows Hosts
  hosts: victim_desktops_b
  gather_facts: no
  vars_files:
    - ../vars/vars.yml
  vars:
    vnc_server_password: "SuperCommerceShabbyBeggar"

  tasks:
    - name: Install common packages amongst Windows hosts
      win_chocolatey:
        name:
          - tightvnc
        state: present
        install_args: "VIEWER_ASSOCIATE_VNC_EXTENSION=1 SERVER_REGISTER_AS_SERVICE=1 SERVER_ADD_FIREWALL_EXCEPTION=1 VIEWER_ADD_FIREWALL_EXCEPTION=1 SERVER_ALLOW_SAS=1 SET_USEVNCAUTHENTICATION=1 VALUE_OF_USEVNCAUTHENTICATION=1 SET_PASSWORD=1 VALUE_OF_PASSWORD={{ vnc_server_password }} SET_USECONTROLAUTHENTICATION=1 VALUE_OF_USECONTROLAUTHENTICATION=1 SET_CONTROLPASSWORD=1 VALUE_OF_CONTROLPASSWORD={{ vnc_server_password }}"
