---
- name: "Configure ER6 Windows Domain {{ domain_info_sonicbeats.shortname }}"
  hosts: victim_linux_protections
  become: yes
  gather_facts: no
  vars_files:
    - ../vars/vars.yml
  tags:
    - joindomain
    - scenariop
    - linux

  tasks:
    - ansible.builtin.include_tasks: configure-and-join-domain-linux.yml
      vars:
        linux_hostname: "{{ domain_info_sonicbeats.linux_hostname }}"
        domain_dns_name: "{{ domain_info_sonicbeats.dns_domain_name }}"
        domain_admin_user: "{{ domain_info_sonicbeats.admin_user }}"
        domain_admin_pass: "{{ domain_info_sonicbeats.admin_pass }}"
        ad_ip_addr: "{{ domain_info_sonicbeats.ad_ip_addr }}"
        tuned_profile: "virtual-guest"
