---
- name: "Configure ER6 Windows Domain {{ domain_info_sonicbeats.shortname }}"
  hosts: victim_mac_protections
#  become: yes
  gather_facts: yes
  vars_files:
    - ../vars/vars.yml
  tags:
    - joindomain
    - scenariop

  tasks:
    - ansible.builtin.include_role:
        name: evals_macos
      vars:
        domain_shortname: "{{ domain_info_sonicbeats.shortname }}"
        dns_domain_name: "{{ domain_info_sonicbeats.dns_domain_name }}"
        admin_user: "{{ domain_info_sonicbeats.admin_user }}"
        admin_pass: "{{ domain_info_sonicbeats.admin_pass }}"
        xcode_download_link: "XCODE_XIP_PACKAGE_URL"
        ad_ip_addr: "{{ domain_info_sonicbeats.ad_ip_addr }}"
        join_domain: true
