---
- name: configure remote workers
  hosts: remote_workers
  gather_facts: no
  vars_files:
    - ../vars/vars.yml

  tasks:
    - name: Create user accounts red admins
      ansible.windows.win_user:
        name: "{{ item.username }}"
        password: "{{ item.password }}"
        fullname: "{{ item.firstname }}"
        password_never_expires: yes
        state: present
        groups:
          - Administrators
          - Remote Desktop Users
      loop: "{{ red_users }}"

    - name: Ensure devadmin does not expire
      ansible.windows.win_user:
        name: "devadmin"
        password_never_expires: yes
        state: present
        account_disabled: no
        account_locked: no
        password_expired: no
