---
- name: "Create directory for gpo files: {{ deploy_dir }}"
  ansible.windows.win_file:
    path: "{{ deploy_dir }}"
    state: directory

- name: "Copy gpo folder to DC: {{ gpo_src_dir }}"
  ansible.windows.win_copy:
    src: "{{ gpo_src_dir }}"
    dest: "{{ deploy_dir }}"

# ignore errors in cases where we run offline
# todo: update playbook to tag online-only tasks
- name: install nuget provider
  ansible.windows.win_shell: |
    Install-PackageProvider -Name Nuget -Force
  ignore_errors: yes

# ignore errors in cases where we run offline
# todo: update playbook to tag online-only tasks
- name: Install GPOTools module
  win_psmodule:
    name: GPOTools
    state: present
    accept_license: yes
  ignore_errors: yes

- name: "Restore GPO policies in: {{ gpo_dst_dir }}"
  win_shell: Restore-GptPolicy -Path .
  args:
    chdir: "{{ gpo_dst_dir }}"

# links directly to domain are not backed up/restored by gpotools, so manually link them
- name: Link GPO policies
  win_shell: |
    New-GPLink -Name "{{ evals_range }}-File Print Sharing" -Target "dc={{ domain_shortname }},dc={{ domain_tld}}"
    New-GPLink -Name "{{ evals_range }}-GP1" -Target "dc={{ domain_shortname }},dc={{ domain_tld}}"
    New-GPLink -Name "{{ evals_range}}-GP2" -Target "dc={{ domain_shortname }},dc={{ domain_tld}}"
    New-GPLink -Name "{{ evals_range}}-GP3" -Target "dc={{ domain_shortname }},dc={{ domain_tld}}"
    New-GPLink -Name "{{ evals_range}}-GP4" -Target "dc={{ domain_shortname }},dc={{ domain_tld}}"
    New-GPLink -Name "{{ evals_range}}-GP5" -Target "dc={{ domain_shortname }},dc={{ domain_tld}}"
  ignore_errors: yes

- name: Cleanup
  ansible.windows.win_file:
    path: "{{ deploy_dir }}"
    state: absent
