---
- name: Copy resolv dns configuration
  copy:
    src: "../files/redirectors/resolv.conf"
    dest: "/etc/resolv.conf"
    mode: '0644'
    owner: root
    group: root

- name: Install redirector deps and useful tools
  ansible.builtin.apt:
    pkg:
      - curl
      - etckeeper
      - iptables-persistent
      - git
      - packagekit
      - resolvconf
      - tuned
      - tuned-utils
    state: present
    update_cache: yes

- name: Configure redirect script for host
  template:
    src: "../files/redirectors/enable-traffic-forwarding-rules.sh.j2"
    dest: "/usr/local/bin/enable-traffic-forwarding-rules.sh"
    mode: '0755'
    group: root
    owner: root

- name: Copy disable script
  copy:
    src: "../files/redirectors/disable-traffic-forwarding-rules.sh"
    dest: "/usr/local/bin/"
    mode: '0755'
    owner: root
    group: root

- name: Copy print script
  copy:
    src: "../files/redirectors/print-traffic-forwarding-rules.sh"
    dest: "/usr/local/bin/"
    mode: '0755'
    owner: root
    group: root

- name: Copy sysctl conf
  copy:
    src: "../files/redirectors/98-er6.conf"
    dest: "/etc/sysctl.d/"
    mode: '0644'
    owner: root
    group: root

- name: Configure redirect netplan for host
  template:
    src: "../files/redirectors/redirect1-51-ens6.yaml.j2"
    dest: "/etc/netplan/51-aws-secondary-nic.yaml"
    mode: '0644'
    group: root
    owner: root

- name: Apply sysctl conf
  ansible.builtin.shell: |
    sysctl --system
  ignore_errors: yes

- name: Apply netplan rules
  ansible.builtin.shell: |
    netplan --debug apply
  ignore_errors: yes

- name: Flush iptables rules
  ansible.builtin.command: iptables -t nat -v -F
  ignore_errors: yes
  become: yes

- name: Process forwarding rules
  ansible.builtin.command: /usr/local/bin/enable-traffic-forwarding-rules.sh
  async: 60
  poll: 5
  ignore_errors: yes
  become: yes

- name: Save and persist forwarding rules
  ansible.builtin.shell: |
    sudo netfilter-persistent save
  ignore_errors: yes
  become: yes
