#!/bin/bash
# Template to capture cmake variables for use in supporting scripts

CONFIG_ENC_KEY=@CONFIG_ENC_KEY@
CONFIG_PATH_ENV=@CONFIG_PATH_ENV@
CONFIG_FILENAME_ENV=@CONFIG_FILENAME_ENV@
MODULE_USERNAME=@MODULE_USERNAME@
CERT_PATH_ENV=@CERT_PATH_ENV@
HEADER_PATH_ENV=@HEADER_PATH_ENV@