samplehandler1: 
  host: 127.0.0.1
  port: 8080
  enabled: true
samplehandler2: 
  host: 127.0.0.1
  port: 443
  cert_file: /dummy/https/cert
  key_file: /dummy/https/key
  enabled: true
samplehandler3: 
  host: 127.0.0.1
  port: 447
  enabled: false
samplehandler4: 
  host: 127.0.0.1
  port: 80
  enabled: false
samplehandler5: 
  host: 127.0.0.1
  port: 8443
  cert_file: /dummy/samplehandler5/cert
  key_file: /dummy/samplehandler5/key
  enabled: true
