[package]
name = "obfuscateresource"
version = "0.1.0"
edition = "2021"

[lib]
name = "obfuscateresource"
path = "src/lib.rs"
proc-macro = true

[dependencies]


aes = "0.8.3"
base64 = "0.21.3"
ctr = "0.9.2"
hex = "0.4.3"
miniz_oxide = "0.7.2"
proc-macro2 = "1.0.67"
rand = "0.8.5"
syn = { version = "2.0.31", features = ["extra-traits"] }
