---
- name: configure bastion
  hosts: b_desk_1
  gather_facts: no
  vars_files:
    - ../vars/vars.yml

  tasks:
    - name: Add bastion admin as local admin
      ansible.windows.win_group_membership:
        name: Administrators
        members:
          - "{{ sub_b_domain.shortname| upper }}\\Domain Admins"
          - "{{ sub_a_domain.shortname| upper }}\\Domain Admins"

    - name: Add admins to RDP group
      ansible.windows.win_group_membership:
        name: Remote Desktop Users
        members:
          - "{{ sub_b_domain.shortname| upper }}\\{{ sub_b_domain.backup_admin_group }}"
          - "{{ sub_b_domain.shortname| upper }}\\Domain Admins"
          - "{{ sub_b_domain.shortname| upper }}\\Domain Users"

    - name: Install bastion specific software
      win_chocolatey:
        name:
          - sql-server-management-studio
          - sql-server-express
        state: present

    - name: Manage tools directory
      win_file:
        path: "{{ red_dev.jumpbox_dev_dir }}"
        state: directory

    - name: Copy sql server files over
      ansible.windows.win_copy:
        src: ../files/bastion
        dest: "{{ red_dev.jumpbox_dev_dir }}"

    - name: Windows Firewall rule TCP 1433
      community.windows.win_firewall_rule:
        name: Permit SQL
        localport: "1433"
        action: allow
        direction: in
        protocol: tcp
        profiles: domain
        state: present
        enabled: yes

    - name: NetBNMB Creation (users)
      ansible.windows.win_shell: "Invoke-Sqlcmd -ServerInstance localhost -InputFile {{ red_dev.jumpbox_dev_dir }}/sql_srv/netbnmb_creation_with_user.sql"
      register: sql_install_result
      ignore_errors: yes

    - name: Insert data into MSSQL
      ansible.windows.win_powershell:
        script: |
          '{{ red_dev.jumpbox_dev_dir }}/sql_srv/insert_data_into_mssql.ps1 -csvPath {{ red_dev.jumpbox_dev_dir }}/sql_srv/users.csv'
      register: insert_data_result
