---
- name: Disable Windows Update Service
  hosts: win_desktops,win_servers
  gather_facts: false

  tasks:
    - name: Disable windows update service
      win_shell: |
        gpupdate /force
        stop-service -DisplayName "Windows Update"
        get-service -DisplayName "Windows Update" | Set-Service -StartupType "Disabled"
