---
- name: Start vms on boot
  hosts: b_srv_kvm
  become: yes
  gather_facts: no
  vars_files:
    - ../vars/vars.yml

  tasks:
    - name: set vms to start on boot
      ansible.builtin.shell: |
        virsh autostart fedora2
        virsh autostart test1
        virsh autostart test2


    - name: Disable sssd global catalog usage
      lineinfile:
        dest: /etc/sssd/sssd.conf
        state: present
        backup: yes
        insertafter: EOF
        line: 'ad_enable_gc = False'

    - name: Increase sssd timeout
      lineinfile:
        dest: /etc/sssd/sssd.conf
        state: present
        backup: yes
        insertafter: EOF
        line: 'krb5_auth_timeout = 30'
