---
- name: Disable kernel updates
  hosts: b_srv_kvm
  become: yes
  gather_facts: no
  vars_files:
    - ../vars/vars.yml

  tasks:
    - name: disable kernel updates
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../files/51disable-kernel-updates"
        dest: "/etc/apt/apt.conf.d/51disable-kernel-updates"
        mode: '0644'
        owner: root
        group: root
