---
- name: Lock linux kernel version
  hosts: b_srv_kvm
  become: yes
  gather_facts: no
  vars_files:
    - ../vars/vars.yml

  tasks:
    - name: Lock kernel at version
      ansible.builtin.shell: |
        sudo apt-mark hold $(uname -r)
        sudo apt-mark hold linux-image-generic linux-headers-generic
        sudo apt-mark hold linux-image-aws linux-headers-aws
