---
- name: Join hosts to Sub A domain
  hosts: a_win_desktops,a_non_ad_win_servers
  gather_facts: no
  vars_files:
    - ../vars/vars.yml

  tasks:
    - name: Configure A DNS to use AD Server
      ansible.windows.win_dns_client:
        adapter_names: '*'
        dns_servers:
          - "{{ sub_a_domain.ad_ip_addr }}"
    - name: Join Sub A AD Domain
      microsoft.ad.membership:
        dns_domain_name: "{{ sub_a_domain.dns_domain_name }}"
        domain_admin_user: "{{ sub_a_domain.shortname}}\\{{ sub_a_domain.admin_user }}"
        domain_admin_password: "{{ sub_a_domain.admin_pass }}"
        state: domain
        reboot: yes
