#!/usr/bin/env bash
# ------------------------------------------------------------------
# [Author] mbutt / infra team
#          * Requires Certificate Authority key and certificate to be associated with AWS Client VPN
#
#          Using the base OpenVPN configuration generated by the cloud provider (e.g. AWS), this script
#          will download the profile, make any necessary modifications (e.g. add friendly name, add keepalive),
#          generate client certificate and associated keys, and sign the certificates with the CA key so they
#          will be considered valid.
#
# ------------------------------------------------------------------

# script meta
SUBJECT=vpn-create-user
VERSION=1.1.1
USAGE="Usage: vpn-create-user"

# Default profile counts (used when no CLI args provided)
DEFAULT_OPERATOR_COUNT=6

# Profile counts (will be set by CLI args or defaults)
OPERATOR_COUNT=""

# Will be generated dynamically based on counts
USERS=""

# global timestamp variable
TIMESTAMP=$(date +'%Y%m%d%H%M')

# working dir to keep things clean
WORKING_PREFIX_DIR="messy"

# configuration
EVAL_PREFIX="er7"
USER_DIR="${EVAL_PREFIX}-vpn"

echoerr() { printf "%s\n" "$*" >&2; }
info() { echoerr "[INFO]    $*"; }
warning() { echoerr "[WARNING] $*"; }
error() { echoerr "[ERROR]   $*"; }
fatal() {
    echoerr "[FATAL]   $*"
    exit 1
}

# client certs
CLIENT_KEY_FILE="client.key"
CLIENT_CRT_FILE="client.crt"
PUBLISH_ROOT_DIR="publish"
PUBLISH_INTERNAL_DIR="${PUBLISH_ROOT_DIR}/internal"
CLIENT_CRT_OUTPUT_DIR="${PUBLISH_ROOT_DIR}/crt-files"

# vendor name argument maps to RANGE_NAME variable
RANGE_NAME=""
RANGE_TYPE=""
PRETTY_RANGE_TYPE=""
BASE_VPN_CFG=""
AWS_VPN_ENDPOINT_ID=""
CA_CERT_KEY_FILE=""
CA_CERT_PEM_FILE=""
SED=gsed

# check for gsed, otherwise sed
if ! type "$SED" >/dev/null; then
    SED=sed
fi

############################################################
# Help                                                     #
############################################################
help() {
    # Display Help
    echo "Generate VPN configuration profiles for the specified range. Vendor name, and range type (either detection or protection), must be specified."
    echo "Certificate and key assumed to be on disk, used to sign client certificates for VPN profiles. "
    echo
    echo "Currently requires CVPN ID and active AWS login to use. "
    echo
    echo "Syntax: vpn-create-user.sh -v VENDOR_NAME -[d|p|m] [-e CVPN_ID] [-c CERT_FILE] [-k KEY_FILE] [-o NUM] [-V NUM] [-b NUM] [-i NUM] [-h]"
    echo "options:"
    echo "   -h     Print this Help."
    echo "   -v     Vendor name."
    echo "   -d     Detections range type."
    echo "   -p     Protections range type."
    echo "   -m     Managed Services range type."
    echo "   -e     AWS Client VPN endpoint ID (e.g. cvpn-endpoint-xyzabc)."
    echo "   -c     Specify path to CA certificate file (in PEM format) to use (default ${CA_CERT_PEM_FILE})."
    echo "   -k     Specify path to CA private key, which matches CA certificate to use (default ${CA_CERT_KEY_FILE})."
    echo "   -o     Number of operator profiles to generate (default: ${DEFAULT_OPERATOR_COUNT})."
    echo
    echo
}

############################################################
# Reminder post run                                        #
############################################################
reminder() {
    warning "Add public certificate to Azure VPN Gateway to authorize VPN connections."
}

############################################################
# Handle command line args                                 #
# -- colon after option name means option takes args       #
############################################################
while getopts ":hv:dpme:c:k:o:" option; do
    case $option in
    h) # display Help
        help
        exit
        ;;
    v) # Enter a vendor name
        RANGE_NAME=$OPTARG
        ;;
    d) # detections type
        RANGE_TYPE="detections"
        PRETTY_RANGE_TYPE="Detections"
        ;;
    p)
        RANGE_TYPE="protections"
        PRETTY_RANGE_TYPE="Protections"
        ;;
    m)
        RANGE_TYPE="er7"
        PRETTY_RANGE_TYPE="ManagedServices"
        ;;
    e)
        AWS_VPN_ENDPOINT_ID=$OPTARG
        ;;
    c)
        info "using custom CA certificate pem file..."
        CA_CERT_PEM_FILE="$OPTARG"
        ;;
    k)
        info "using custom CA key file..."
        CA_CERT_KEY_FILE="$OPTARG"
        ;;
    o)
        OPERATOR_COUNT=$OPTARG
        info "Setting operator profile count to: $OPERATOR_COUNT"
        ;;
    \?) # Invalid option
        error "Invalid option"
        exit
        ;;
    esac
done

# Early exit if vendors are not provided
if [[ ! "${RANGE_NAME}" ]]; then
    fatal "Please provide vendor names (option -v)"
fi

# Set defaults if not provided via CLI
[[ -z "$OPERATOR_COUNT" ]] && OPERATOR_COUNT=$DEFAULT_OPERATOR_COUNT

info "Profile counts - Operator: $OPERATOR_COUNT"

# Generate user list dynamically
generate_user_list() {
    local users_list=""

    # Generate operator profiles
    for ((i=1; i<=OPERATOR_COUNT; i++)); do
        users_list="$users_list operator$i"
    done

    echo "$users_list"
}

USERS=$(generate_user_list)
info "Creating VPN users: $USERS"
info "Total profiles to generate: $OPERATOR_COUNT"

############################################################
# Globals                                                  #
############################################################

# oVPN files
OVPN_FILE="OpenVPN_vpnconfig.ovpn"
OVPN_FILE_USER="OpenVPN"

# ca certs
CA_CERT_DIR='out/keys'

# Check if CA certificate and key were specified
if [[ ! "${CA_CERT_KEY_FILE}" ]]; then
    info "Using default key file for CA..."
    CA_CERTKEY_PAIR_FILE="${CA_CERT_DIR}/${RANGE_NAME}-caCert.pfx"
fi

if [[ ! "${CA_CERT_PEM_FILE}" ]]; then
    info "Using default public cert file for CA..."
    CA_CERT_PEM_FILE="${CA_CERT_DIR}/${RANGE_NAME}-caCert.pem"
fi

CA_CERTKEY_PAIR_FILE="${CA_CERT_DIR}/${RANGE_NAME}-caCert.pfx"
CA_CERT_B64_FILE="${CA_CERT_DIR}/${RANGE_NAME}-caCert.base64"

###### NOTE ######
# CHANGE THE LINES BELOW TO MATCH THE ORG YOU ARE GENERATING CERTIFICATES FOR.
##################
# tmp directory used during profile generation to reduce clutter. safe to delete directory after successful script execution.
TMP_PROFILE_WORKING_DIR="${WORKING_PREFIX_DIR}/tmp-working-${RANGE_NAME}-${RANGE_TYPE}-${TIMESTAMP}"

# Directory that will contain the zipped profiles for all users
PROFILE_OUTPUT_DIRECTORY="${WORKING_PREFIX_DIR}/vpn-profiles-${RANGE_NAME}-${RANGE_TYPE}-${TIMESTAMP}"

# for situations where it matters (like vpn device name in azure, differentiate between detections and protections
vendor_name="${RANGE_NAME}"

############################################################
# Main functions                                           #
############################################################

ensure_cert_dir_exists() {
    info "creating certificate directory: ${CA_CERT_DIR}"
    mkdir -p "${CA_CERT_DIR}"
}

make_output_dirs() {
    info "Creating output directory structure"

    info "Creating internal profiles directory: ${PUBLISH_INTERNAL_DIR}"
    mkdir -p ${PUBLISH_INTERNAL_DIR}

    info "Creating temporary working directory: ${TMP_PROFILE_WORKING_DIR}"
    mkdir -p "${TMP_PROFILE_WORKING_DIR}"

    info "Creating profile output directory: ${PROFILE_OUTPUT_DIRECTORY}"
    mkdir -p "${PROFILE_OUTPUT_DIRECTORY}"

    info "Creating certificate output directory: ${CLIENT_CRT_OUTPUT_DIR}"
    mkdir -p "${CLIENT_CRT_OUTPUT_DIR}"

    info "Directory structure created successfully"
}

check_cert_on_disk() {
    info "Validating cert export was successful"
    # If unable to pull the cert exit. No use moving on.
    if ! [ -s "${CA_CERT_PEM_FILE}" ]; then
        fatal "$CA_CERT_PEM_FILE does not exist."
        # shellcheck disable=SC2317
        exit 1
    fi
}

aws_cleanup_vpn_cfg() {
    # cleanup vpn profile that was downloaded from AWS
    info "cleaning up $1"
    # add a random string at the beginning of the hostname
    ${SED} -i "4s/remote /remote ${RANGE_NAME}\./" "$1"
    ${SED} -i '/^verb 3.*/a keepalive 0 0' "$1"
    ${SED} -i '/^keepalive.*/a setenv FRIENDLY_NAME "@@USER@@ range vpn"' "$1"
    cat <<'ADDCERTEOL' >>"$1"
# P2S client certificate
<cert>
$CLIENTCERTIFICATE
</cert>

# P2S client certificate private key
<key>
$PRIVATEKEY
</key>
ADDCERTEOL
    dos2unix "$1"
    info "Done with the fixing of the vpn configuration files..."
}

aws_download_vpn_base_profile() {
    # download
    info "Downloading VPN profile from AWS via aws cli (requires active aws login session)"
    info "Endpoint ID: ${AWS_VPN_ENDPOINT_ID}"

    # put config in place and clean it up
    # mv "${localfile}"/OpenVPN/vpnconfig.ovpn "${localfile}"/OpenVPN_vpnconfig.ovpn
    aws ec2 export-client-vpn-client-configuration --client-vpn-endpoint-id "${AWS_VPN_ENDPOINT_ID}" --output text >${OVPN_FILE}
    aws_cleanup_vpn_cfg ${OVPN_FILE}
    BASE_VPN_CFG=${OVPN_FILE}
}

create_profiles() {
    local total_users=$(echo $USERS | wc -w)
    local current_user=0

    info "Creating profiles for $total_users users"
    info "Profile creation started at $(date)"

    for user in ${USERS}; do
        ((current_user++))
        info "Processing user $current_user/$total_users: $user"

        PROFILE_DIR="${TMP_PROFILE_WORKING_DIR}/${USER_DIR}-${RANGE_NAME}-${user}"
        info "Creating profile directory: $PROFILE_DIR"
        mkdir -p "${PROFILE_DIR}"

        info "Copying base VPN config for $user"
        cp -af "${BASE_VPN_CFG}" "${PROFILE_DIR}"/${OVPN_FILE}

        info "Generating private key for $user"
        ipsec pki --gen --outform pem >"${PROFILE_DIR}"/${CLIENT_KEY_FILE}

        info "Generating and signing certificate for $user"
        ipsec pki --pub --in "${PROFILE_DIR}"/${CLIENT_KEY_FILE} | ipsec pki --issue --cacert "${CA_CERT_PEM_FILE}" --cakey "${CA_CERT_KEY_FILE}" --dn "CN=${RANGE_TYPE}-${user}" --san "${RANGE_TYPE}-${user}" --flag clientAuth --outform pem >"${PROFILE_DIR}"/${CLIENT_CRT_FILE}

        info "Embedding certificates into VPN config for $user"
        export PRIVATEKEY=$(<"${PROFILE_DIR}"/${CLIENT_KEY_FILE})
        export CLIENTCERTIFICATE=$(<"${PROFILE_DIR}"/${CLIENT_CRT_FILE})
        envsubst <"${PROFILE_DIR}"/${OVPN_FILE} >"${PROFILE_DIR}"/${OVPN_FILE}.tmp

        local final_profile="${RANGE_NAME}_${RANGE_TYPE}_${OVPN_FILE_USER}_${user}.ovpn"
        mv -f "${PROFILE_DIR}"/${OVPN_FILE}.tmp "${PROFILE_DIR}"/$final_profile
        ${SED} -i "s/@@USER@@/${RANGE_TYPE}-${user}-${RANGE_NAME}/g" "${PROFILE_DIR}"/$final_profile

        info "Creating ZIP archive for $user"
        zip -j -X "${PROFILE_OUTPUT_DIRECTORY}"/${final_profile}.zip "${PROFILE_DIR}"/$final_profile

        info "Copying certificate file for CRL generation: $user"
        cp -af "${PROFILE_DIR}"/${CLIENT_CRT_FILE} "${CLIENT_CRT_OUTPUT_DIR}"/"${RANGE_TYPE}-${RANGE_NAME}-${user}-${CLIENT_CRT_FILE}"

        info "Completed profile for $user ($current_user/$total_users)"
    done

    info "Profile creation completed at $(date)"
    info "All $total_users profiles created successfully"
}

organize_vendor_profiles() {
    local profile_collection_dir="${PROFILE_OUTPUT_DIRECTORY}/${RANGE_NAME}_VPN_Profiles_${PRETTY_RANGE_TYPE}"
    info "Creating profile collection directory: $profile_collection_dir"
    mkdir "$profile_collection_dir"

    info "Copying all profiles to collection directory"
    cp -af "${PROFILE_OUTPUT_DIRECTORY}"/*"${RANGE_NAME}"_${RANGE_TYPE}*.zip "$profile_collection_dir"/

    local internal_files=$(ls "${PROFILE_OUTPUT_DIRECTORY}"/"${RANGE_NAME}"*{operator,}* 2>/dev/null | wc -l)
    info "Copying $internal_files internal profiles to ${PUBLISH_INTERNAL_DIR}/"
    cp -af "${PROFILE_OUTPUT_DIRECTORY}"/"${RANGE_NAME}"*{operator,}* ${PUBLISH_INTERNAL_DIR}/ 2>/dev/null || info "No internal profiles found"

    info "Profile organization completed - profiles available in ${PUBLISH_ROOT_DIR} subdirectories"
}

vpn_main() {
    info "=== VPN Profile Generation Started ==="
    info "Execution started at $(date)"
    info "Range: $RANGE_NAME, Type: $RANGE_TYPE"
    info "Total profiles to generate: $(OPERATOR_COUNT)"

    info "Step 1: Validating certificates on disk"
    check_cert_on_disk

    info "Step 2: Creating output directories"
    make_output_dirs

    info "Step 3: Downloading base VPN profile from AWS"
    aws_download_vpn_base_profile

    info "Step 4: Creating individual user profiles"
    create_profiles

    info "Step 5: Organizing profiles by type"
    organize_vendor_profiles

    info "=== VPN Profile Generation Completed ==="
    info "Execution completed at $(date)"
    info "Output directory: ${PROFILE_OUTPUT_DIRECTORY}"
    info "Internal profiles: ${PUBLISH_INTERNAL_DIR}"
}

vpn_main
