version: BUILD{build}

image: Visual Studio 2019
shallow_clone: true

configuration:
- Debug
- Release

before_build:
  - nuget restore

build:
  project: Quasar.sln
  parallel: true
  verbosity: minimal

artifacts:
- path: Bin
  name: binaries